### PR TITLE
fix: interstitials and rewarded ads

### LINKED ISSUE #6: [🐛] 🔥 Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.
HI,

I was testing this application and I fall into this issue.

PR coming soon.

## Issue

After installing the `main` branch, I compile the library on iOS, everything was fine expected that the application is not starting due to:

```
Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.
```

---

## Project Files

No specific project file required.

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 6.09 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    Yarn: 1.12.3 - ~/.npm-packages/bin/yarn
    npm: 7.18.1 - ~/.npm-packages/bin/npm
    Watchman: 2021.11.01.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 19, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31
      Build Tools: 23.0.1, 24.0.2, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.3, 28.0.0, 28.0.2, 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-16 | Google APIs Intel x86 Atom, android-18 | Google APIs Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs ARM EABI v7a, android-21 | Google APIs Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs ARM EABI v7a, android-26 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_131 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.1 => 17.0.2 
    react-native: ^0.66 => 0.66.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [X] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

### PR DESCRIPTION
**Pull request by dylancom**
### Description
Fixes #6 & #16

- [x] Make it work on iOS
- [x] Make it work on Android

### CODE REVIEW

File: android/src/main/java/io/invertase/googleads/ReactNativeAppModule.java [hunk 1]
```diff
@@ -0,0 +1,173 @@
+package io.invertase.googleads;
```
Comment (mikehardy) [inline android/src/main/java/io/invertase/googleads/ReactNativeAppModule.java:1]: Oh wow! Did not realize I completely missed part of the module loading infrastructure. Oof

File: android/src/main/java/io/invertase/googleads/common/RCTConvert.java [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+        }
+    }
+
+    return map;
+  }
+
+  // TODO Remove me - also in SharedUtils
+  public static WritableMap readableMapToWritableMap(ReadableMap map) {
+    WritableMap writableMap = Arguments.createMap();
+    // https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/WritableNativeMap.java#L54
```
Comment (mikehardy) [inline android/src/main/java/io/invertase/googleads/common/RCTConvert.java:104]: main branch name reference

```suggestion
    // https://github.com/facebook/react-native/blob/main/ReactAndroid/src/main/java/com/facebook/react/bridge/WritableNativeMap.java#L58
```

File: android/src/main/java/io/invertase/googleads/common/RCTConvert.java [hunk 3]
```diff
@@ -0,0 +1,118 @@
...
+    writableMap.merge(map);
+    return writableMap;
+  }
+
+  public static Map<String, Object> toHashMap(ReadableMap readableMap) {
+    // https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableNativeMap.java#L216
```
Comment (mikehardy) [inline android/src/main/java/io/invertase/googleads/common/RCTConvert.java:110]: main branch ref, and line changed

```suggestion
    // https://github.com/facebook/react-native/blob/main/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableNativeMap.java#L263
```

File: android/src/main/java/io/invertase/googleads/common/RCTConvert.java [hunk 4]
```diff
@@ -0,0 +1,118 @@
...
+    return readableMap.toHashMap();
+  }
+
+  public static List<Object> toArrayList(ReadableArray readableArray) {
+    // https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableNativeArray.java#L175
```
Comment (mikehardy) [inline android/src/main/java/io/invertase/googleads/common/RCTConvert.java:115]: main branch ref, and line changed

```suggestion
    // https://github.com/facebook/react-native/blob/main/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableNativeArray.java#L140
```

**Review by mikehardy — CHANGES_REQUESTED** [review]
Looks great - will merge pending those comment lines
I haven't tested but I know this is an improvement and I know you are all over this, so just going to merge as soon as the annotations for inclusive language are nailed

Thanks!

**Review by mikehardy — APPROVED** [review]
boom - let's go :-)
